FEAT: Added bulk operation in database file and updated output format in request processor
abdullahalhoothy/backend_common pull request #7
Opened 2024-10-23 20:44 UTC by shehram-tahir

2024-10-23 21:05 UTC, abdullahalhoothy requested changes

2024-10-23 21:05 UTC, abdullahalhoothy commented on dtypes/response_dtypes.py
> +    data: T
Why is this still here .I thought we agreed to remove it

2024-10-23 21:07 UTC, shehram-tahir commented on dtypes/response_dtypes.py
> +    data: T
We might need to use this validation, so I have not removed it. But I have removed it's usage, so it is not in use anymore

2024-10-23 21:31 UTC, abdullahalhoothy requested changes

2024-10-23 21:31 UTC, abdullahalhoothy commented on request_processor.py
> +    return output
```suggestion

    res_body = output_type(**output)
    return res_body
```

2024-10-23 21:31 UTC, abdullahalhoothy commented on request_processor.py
>      input_type: Optional[Type[T]],
```suggestion
    input_type: Optional[Type[T]],
    output_type: Type[U],
```

2024-10-24 00:32 UTC, abdullahalhoothy approved these changes

2024-10-24 00:33 UTC, merged